### PR TITLE
added aszanto's notes

### PR DESCRIPTION
**Pull request by aronszanto**

### CODE REVIEW

**Comment by aronszanto** [comment]
@rachtsingh please merge my edits! Thanks.

**Comment by rachtsingh** [comment]
Sorry, I think this PR is bad for a lot of reasons (I think probably you missed that `main.tex`):

1. You didn't recompile `main.pdf`
2. You changed `subsection` -> `section`, even though that's what we're using (since the chapter headings embed a `section` increment inside).
3. I don't think the reference to `7/neural-networks.png` is necessary, and it screws up the compile of `main.pdf`.

**Comment by aronszanto** [comment]
Thanks- will recheck. I had copy pasted the .tex file, need to reread instructions.

**Comment by aronszanto** [comment]
Sorry about that- didn't have a good idea of what was necessary. The picture isn't causing me problems, seems to render correctly in the PDF. Sections changed to subsections, and I compiled main.pdf.

**Comment by rachtsingh** [comment]
Ok, no problem. I'll merge even though I'll change `subsubsection -> subsection` later (I think it was fine as it was before PR).

**Pull request merged**
