### PR TITLE
Added lecture 8 notes

### PR DESCRIPTION
**Pull request by anaroxanapop**
Added lecture 8 notes (.pdf, .tex plus images), modified main.tex and README.md to reference to lecture 8 (and 7).

### CODE REVIEW

**Comment by rachtsingh** [comment]
Looks great! Could you recompile main.pdf and include it in the PR?

**Comment by anaroxanapop** [comment]
Rachtsingh, I am having problems compiling main.tex : ! Package PGF Math Error: Unknown function `of' (in 'of c1').
I only added \import{8/}{8} at the end of the document.

**Comment by anaroxanapop** [comment]
Problem seems to be caused by the fact that we used the following in 8.tex:
\usepackage{graphics}
\usepackage{placeins}
\usepackage{tikz}
\usetikzlibrary{calc, arrows.meta, positioning}
\newcommand{\N}{\mathcal{N}}

Is it ok to add these at top of main.tex or is there another more elegant solution to this? Thanks!

**Comment by rachtsingh** [comment]
Hey, thanks for the quick reply - can you put it into `pagesetup.sty`? That's where we're putting macros, etc.

**Comment by rachtsingh** [comment]
Sorry, just as a heads up - you'll want to pull from master (I just merged another PR).

**Comment by anaroxanapop** [comment]
I put the macros in pagesetup.sty and recompiled main.pdf.
However, after the latest PR you just merged (for lecture 7), I noticed that subsection numbers are off - now Lecture 3 starts with 3.6 (vs. 3.1), etc. for all other lectures.

**Comment by anaroxanapop** [comment]
Nevermind, I looked back at the history of main.pdf and it looks like that is the intended format. Thanks!

**Comment by rachtsingh** [comment]
Yeah, sorry there's an open issue. I'll fix it once I get a chance.

**Comment by rachtsingh** [comment]
Thanks!

**Pull request merged**
